name: Swift

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["6.0"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: setup-swift
        uses: swift-actions/setup-swift@v2.2.0
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
